### ISSUE TITLE
Incorporate NO VOTES into ZoneCandidateList.

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#101]
The puzzle `1-77a0075b` from #1 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/c441e46ab4a8e6c815c4d70c29aa5a4e9b7c94b3/src/pages/index.js#L285-L285

The puzzle was created by Thai Pangsakulyanont on 22-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dtinth** [comment]
From design:

ให้ถือเป็นผู้สมัครอีกคนนึงไปเลย (Re-use component CandidateStatsRow) ใช้ชื่อพรรคว่า “ไม่เลือกใคร” และซ่อนช่ือผู้สมัครและหมายเลขผู้สมัคร (maybe send `props.candidateNumber === 0` and use that to determine whether to show/hide)

**Comment by parnurzeal** [comment]
I will take this one.

**Comment by 0pdd** [comment]
The puzzle `1-77a0075b` has disappeared from the source code, that's why I closed this issue.
