### ISSUE TITLE
Add social meta tag, e.g. open graph image, etc.

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#102]
The puzzle `1-a35fbb61` from #1 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/d82495a0e1d8e980948edafc40c7d48d03acc3d1/src/components/DocumentHead.js#L17-L17

The puzzle was created by Thai Pangsakulyanont on 22-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by iammarkps** [comment]
I'm currently working on this issue

**Comment by p16i** [comment]
Could you please also add an cover image? 

Facebook Share Debugger: https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Felect.thematter.co


Update: please use the image below

![cover (2)](https://user-images.githubusercontent.com/1214890/54874712-5649a680-4e23-11e9-978c-24e2b7e3692a.png)

**Comment by 0pdd** [comment]
The puzzle `1-a35fbb61` has disappeared from the source code, that's why I closed this issue.
