### ISSUE TITLE
CountdownCurtain: Add image

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#106]
The puzzle `1-18867a8f` from #1 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/dcfac822b1d15e8620ab591ff01527de4f46ac7e/src/components/MainLayout.js#L173-L173

The puzzle was created by Thai Pangsakulyanont on 23-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dtinth** [comment]
Design:

![image](https://user-images.githubusercontent.com/193136/54865340-b9412c00-4d96-11e9-8f7d-1a44ce747326.png)

- Use this GIF:
  ![count_live](https://user-images.githubusercontent.com/193136/54865343-bfcfa380-4d96-11e9-9392-8f2948af698a.gif)

- Logo already in source tree
