### ISSUE TITLE
ZoneCandidateList Bug: Calculate goodVotes based on `data.candidates` instead of zoneStats.goodVotes. Problem: To reproduce, time travel to 20190323040304 and open a zone. You can see that I...

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#112]
The puzzle `1-4fde1041` from #1 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/a7189296fd8dc223324bb2f32ccc27a7638f57d8/src/pages/index.js#L289-L294

The puzzle was created by Thai Pangsakulyanont on 23-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by parnurzeal** [comment]
I will take this one.

**Comment by 0pdd** [comment]
The puzzle `1-4fde1041` has disappeared from the source code, that's why I closed this issue.
