### ISSUE TITLE
Implement <PartyStatsRow /> component

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#12]
The puzzle `1-bf73ac08` from #1 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/3d74d66e1b0ac906d99607af8c1fbaa5ecab18b7/src/components/KitchenSink.js#L16-L16

The puzzle was created by Thai Pangsakulyanont on 17-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dtinth** [comment]
(from invision)

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/193136/54496120-45c69700-491e-11e9-9580-ea27807988a2.png">

**Comment by 0pdd** [comment]
The puzzle `1-bf73ac08` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#13](https://github.com/codeforthailand/election-live/issues/13), [#14](https://github.com/codeforthailand/election-live/issues/14) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#13](https://github.com/codeforthailand/election-live/issues/13), [#15](https://github.com/codeforthailand/election-live/issues/15) are still not solved; solved: [#14](https://github.com/codeforthailand/election-live/issues/14).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#13](https://github.com/codeforthailand/election-live/issues/13), [#14](https://github.com/codeforthailand/election-live/issues/14), [#15](https://github.com/codeforthailand/election-live/issues/15).
