### ISSUE TITLE
Party View - implement interactive tab

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#122]
The puzzle `1-c71f393e` from #1 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/3a201df7c72eccc4238f267408bd20aed30cb66d/src/components/PerPartyMemberVoteResult.js#L62-L62

The puzzle was created by Pankamol Srikaew on 23-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by AimeTPGM** [comment]
done on https://github.com/codeforthailand/election-live/pull/137
