### ISSUE TITLE
Update zone tooltip for ElectionMap

### ISSUE THREAD

**Issue by rapee** [codeforthailand/election-live#134]
Before:

<img width="473" alt="Screen Shot 2019-03-23 at 23 31 36" src="https://user-images.githubusercontent.com/924635/54868878-ece67b00-4dc3-11e9-8327-363e486270f6.png">

After:

<img width="558" alt="Screen Shot 2019-03-23 at 23 31 42" src="https://user-images.githubusercontent.com/924635/54868880-ef48d500-4dc3-11e9-90da-65fe175c5eb4.png">

**Comment by unnawut** [comment]
I'll take this one starting in the morning.

**Comment by na399** [comment]
I've managed to achieve this far, but I'm too knackered to continue. 
Anyway, my pull request #143 may help save your time to progress further, @unnawut.

<img width="460" alt="Screenshot 2019-03-24 at 05 35 17" src="https://user-images.githubusercontent.com/13469652/54872444-bb3ad780-4df6-11e9-9632-cbb4564cc5ff.png">

All the best 😉

**Comment by kristw** [comment]
I will take over na. Will merge #143 and take it from there.

**Comment by kristw** [comment]
In master now

![image](https://user-images.githubusercontent.com/1659771/54872874-8728cd80-4d88-11e9-8c83-aad411b5547a.png)

**Comment by kristw** [comment]
working on tooltip for partylist

**Comment by kristw** [comment]
done

![image](https://user-images.githubusercontent.com/1659771/54872965-0cf94880-4d8a-11e9-8894-fa41b6cae3f7.png)

**Comment by kristw** [comment]
Add legend to the top instead because on the side will conflict when zoom in

![image](https://user-images.githubusercontent.com/1659771/54873041-6dd55080-4d8b-11e9-95ef-a9c8e3905acb.png)

**Comment by kristw** [comment]
Closing this issue as completed
