### ISSUE TITLE
PartyDropdown isn't displayed properly on desktop view.

### ISSUE THREAD

**Issue by p16i** [codeforthailand/election-live#157]
Version: v1.0.0-beta.2

`/party` looks like:
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/1214890/54874760-35ce1c00-4e24-11e9-9e52-efc9bdcf10fc.png">

However, according to the design it should look something like this:

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/1214890/54874784-a70dcf00-4e24-11e9-8b75-b6b84c302223.png">

**Comment by unnawut** [comment]
I'm attempting this
