### ISSUE TITLE
Implement <CandidateStatsRow /> component This component displays how many votes a candidate has received.

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#16]
The puzzle `1-db2b4d14` from #1 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/82cfcc413f4b85562d579e63e57093743a75bc07/src/components/CandidateStatsRow.js#L4-L5

The puzzle was created by Thai Pangsakulyanont on 17-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dtinth** [comment]
(From InVision)

<img width="693" alt="image" src="https://user-images.githubusercontent.com/193136/54496535-ffc00200-4922-11e9-8a97-2fa4875494fa.png">

**Comment by dtinth** [comment]
This one is low priority na

**Comment by dodadoa** [comment]
okie I see

**Comment by p16i** [comment]
@dodadoa are you working on this one?

**Comment by dodadoa** [comment]
not anymore

**Comment by 0pdd** [comment]
The puzzle `1-db2b4d14` has disappeared from the source code, that's why I closed this issue.
