### ISSUE TITLE
Electoral district filtering

### ISSUE THREAD

**Issue by dtinth** [codeforthailand/election-live#18]
![image](https://user-images.githubusercontent.com/193136/54545541-72d58100-49d4-11e9-93f8-4bb9988ca6ea.png)

**Comment by 0pdd** [comment]
@dtinth 4 puzzles [#19](https://github.com/codeforthailand/election-live/issues/19), [#20](https://github.com/codeforthailand/election-live/issues/20), [#21](https://github.com/codeforthailand/election-live/issues/21), [#22](https://github.com/codeforthailand/election-live/issues/22) are still not solved.

**Comment by 0pdd** [comment]
@dtinth 3 puzzles [#19](https://github.com/codeforthailand/election-live/issues/19), [#20](https://github.com/codeforthailand/election-live/issues/20), [#21](https://github.com/codeforthailand/election-live/issues/21) are still not solved; solved: [#22](https://github.com/codeforthailand/election-live/issues/22).

**Comment by 0pdd** [comment]
@dtinth 2 puzzles [#19](https://github.com/codeforthailand/election-live/issues/19), [#20](https://github.com/codeforthailand/election-live/issues/20) are still not solved; solved: [#21](https://github.com/codeforthailand/election-live/issues/21), [#22](https://github.com/codeforthailand/election-live/issues/22).

**Comment by 0pdd** [comment]
@dtinth all 4 puzzles are solved here: [#19](https://github.com/codeforthailand/election-live/issues/19), [#20](https://github.com/codeforthailand/election-live/issues/20), [#21](https://github.com/codeforthailand/election-live/issues/21), [#22](https://github.com/codeforthailand/election-live/issues/22).

**Comment by rapee** [comment]
Close due to ชนะถล่มทลาย and ชนะฉิวเฉียด has its own issue on #104, #105
