### ISSUE TITLE
Map: Party list blocks look strange

### ISSUE THREAD

**Issue by p16i** [codeforthailand/election-live#186]
<img width="1283" alt="Screenshot 2019-03-24 17 59 50" src="https://user-images.githubusercontent.com/1214890/54878399-d04b5100-4e5e-11e9-9a69-6ed145c85b93.png">

**Comment by na399** [comment]
There seem to be typos in src/models/information/_map.json, fixed in #188.

**Comment by dodadoa** [comment]
done
