### ISSUE TITLE
Add dropdown arrow to area selection on the top (mobile view)

### ISSUE THREAD

**Issue by paonets** [codeforthailand/election-live#193]
To indicate that it is clickable

**Comment by dtinth** [comment]
![image](https://user-images.githubusercontent.com/193136/54879083-86b33400-4e67-11e9-9b96-9d4eb5814ff8.png)

**Comment by MicroBenz** [comment]
I will do this issue krub. :D

**Comment by MicroBenz** [comment]
PR is ready #194
