### ISSUE TITLE
Implement filtering code for เขตพื้นที่นอกเมือง

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#20]
The puzzle `18-95187052` from #18 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/2f61ae06c11b88bb05b732b4e826e8a3210f275b/src/models/information/_filters.js#L51-L51

The puzzle was created by Thai Pangsakulyanont on 18-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by rapee** [comment]
# 1. เขตพื้นที่เมือง
เขตที่มีความหนาแน่นประชากร 800 คน/ตร.กม. ขึ้นไป (≥ เขตที่หนาแน่นน้อยที่สุดของกทม.)

# 2. เขตพื้นที่นอกเมือง
เขตที่มีความหนาแน่นประชากรน้อยกว่า 800 คน/ตร.กม (< เขตที่หนาแน่นน้อยที่สุดของกรุงเทพฯ)

:pushpin: ข้อ 1-2 ใช้เกณฑ์ความหนาแน่นปชก. เอาจ้า เพราะปชก. ทุกเขต 189,110 คนเท่ากัน ก็เลยให้พี่โฟนช่วยทำข้อมูลขนาดแต่ละเขตเลือกตั้งไว้แล้ว เขตไหนที่มีพื้นที่เยอะกว่า 236.39 ตร.กม. นับเป็นพื้นที่เมือง (ดร. ให้คิดจากขนาดเขตที่ใหญ่ที่สุดในกทม)

**Comment by 0pdd** [comment]
The puzzle `18-95187052` has disappeared from the source code, that's why I closed this issue.
