### ISSUE TITLE
Implement filtering code for Gerrymandering

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#21]
The puzzle `18-c7f367f1` from #18 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/2f61ae06c11b88bb05b732b4e826e8a3210f275b/src/models/information/_filters.js#L59-L59

The puzzle was created by Thai Pangsakulyanont on 18-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by rapee** [comment]
# 3. เขตเลือกตั้งแบ่งโดยคสช.
จังหวัดที่มีรูปแบบเขตเลือกตั้งไม่ตรงกับที่ กกต.จังหวัดกำหนด เนื่องด้วยคำสั่ง คสช.

นครราชสีมา
สุรินทร์
มหาสารคาม
ยโสธร
สกลนคร
อุดรธานี
นครสวรรค์
นครปฐม
เชียงราย
สุโขทัย
ชัยนาท

**Comment by 0pdd** [comment]
The puzzle `18-c7f367f1` has disappeared from the source code, that's why I closed this issue.
