### ISSUE TITLE
Implement filtering code for Swing District

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#22]
The puzzle `18-3c00c6fa` from #18 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/2f61ae06c11b88bb05b732b4e826e8a3210f275b/src/models/information/_filters.js#L67-L67

The puzzle was created by Thai Pangsakulyanont on 18-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by rapee** [comment]
# 4. เขตเลือกตั้งที่ไม่มีฐานเสียงชัดเจน (Swing Province)*
จังหวัดที่มีผลคะแนนเลือกตั้งปี 54 ของพรรคอันดับ 1 กับอันดับ 2 ห่างกันไม่ถึง 5%

อำนาจเจริญ
นครนายก
ราชบุรี
ปราจีนบุรี
ชลบุรี
กรุงเทพมหานคร
กำแพงเพชร
สุโขทัย
สมุทรสาคร

:pushpin: ข้อ 4 นี่ต้องใช้เป็นจังหวัด เพราะมันเป็นการเทียบกับปี 54 ซึ่งเขตเลือกตั้งไม่ตรงกัน

**Comment by 0pdd** [comment]
The puzzle `18-3c00c6fa` has disappeared from the source code, that's why I closed this issue.
