### ISSUE TITLE
Prevent users from deactivating the time machine panel inadvertently

### ISSUE THREAD

**Issue by sorawee** [codeforthailand/election-live#232]
When the first (or the last) entry in the time machine panel is focused, hitting the left (or right) key will deactivate the panel. Not only is this unintuitive, but it also makes navigation by holding the left or right key difficult in a sense that users need to be careful not hitting the edge, or else the panel will be closed.

**Comment by dtinth** [comment]
Thanks for sending the issue. Busy right now, would you like to submit a PR? ;)

**Comment by p16i** [comment]
Probably because of this line: https://github.com/codeforthailand/election-live/blob/master/src/components/TimeMachine.js#L38
```
goBackTo(Math.min(dirs.length - 1, Math.max(0, browsingIndex + dt)))
```
Adding a condition for `browsingIndex` should be sufficient to solve the problem.

**Comment by sorawee** [comment]
Sure, will submit a PR.

IMO, a better place to change is https://github.com/codeforthailand/election-live/blob/master/src/components/TimeMachine.js#L54
