### ISSUE TITLE
[UI] Implement <Loading /> component

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#26]
The puzzle `1-4ee38d3c` from #1 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/32979001c550962547c83ba502a8b475c9434997/src/components/NationwideSummaryView.js#L12-L12

The puzzle was created by Thai Pangsakulyanont on 18-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dtinth** [comment]
Design:

![count_white](https://user-images.githubusercontent.com/193136/54851429-79d5f980-4d1c-11e9-9ea0-2b0c24f8bdf8.gif)

First version, we can use this .gif file verbatim.

**Comment by 0pdd** [comment]
The puzzle `1-4ee38d3c` has disappeared from the source code, that's why I closed this issue.
