### ISSUE TITLE
Adjust NavBar style according to latest design (desktop).

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#29]
The puzzle `1-daf3173f` from #1 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/02bf204e19a1ae84981e7dc82d7e685257fb3f45/src/components/NavBar.js#L6-L6

The puzzle was created by Thai Pangsakulyanont on 18-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dtinth** [comment]
New NavBar style looks like this:

![image](https://user-images.githubusercontent.com/193136/54560459-fd2ddd00-49f4-11e9-9df6-f4916113384f.png)

**Comment by 0pdd** [comment]
The puzzle `1-daf3173f` has disappeared from the source code, that's why I closed this issue.
