### ISSUE TITLE
Election Map

### ISSUE THREAD

**Issue by dtinth** [codeforthailand/election-live#30]
<img width="396" alt="image" src="https://user-images.githubusercontent.com/193136/54581884-27a58780-4a41-11e9-8521-4f3f329d4c09.png">

**Comment by 0pdd** [comment]
@dtinth the puzzle [#31](https://github.com/codeforthailand/election-live/issues/31) is still not solved.

**Comment by dtinth** [comment]
@rapee @Director99 

You can decide the name and the structures for props you want to use na krub. The general idea is that the component decides the shape of the props that’s necessary to display all data. This is the “presentational component”.

Then we can create a “container component” to bridge the component to the data source.

See this article for more info: [Presentational and Container Components](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0)

**Comment by 0pdd** [comment]
@dtinth 2 puzzles [#31](https://github.com/codeforthailand/election-live/issues/31), [#71](https://github.com/codeforthailand/election-live/issues/71) are still not solved.

**Comment by 0pdd** [comment]
@dtinth the puzzle [#71](https://github.com/codeforthailand/election-live/issues/71) is still not solved; solved: [#31](https://github.com/codeforthailand/election-live/issues/31).

**Comment by 0pdd** [comment]
@dtinth 2 puzzles [#31](https://github.com/codeforthailand/election-live/issues/31), [#71](https://github.com/codeforthailand/election-live/issues/71) are still not solved.

**Comment by 0pdd** [comment]
@dtinth the puzzle [#31](https://github.com/codeforthailand/election-live/issues/31) is still not solved; solved: [#71](https://github.com/codeforthailand/election-live/issues/71).

**Comment by 0pdd** [comment]
@dtinth all 2 puzzles are solved here: [#31](https://github.com/codeforthailand/election-live/issues/31), [#71](https://github.com/codeforthailand/election-live/issues/71).

**Comment by dtinth** [comment]
All puzzles solved, closing
