### ISSUE TITLE
Setup deployment to live environment.

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#34]
The puzzle `1-f7fafd1b` from #1 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/12cc5ec75942427a48303dacff7356b138bc3970/.circleci/config.yml#L42-L42

The puzzle was created by Thai Pangsakulyanont on 19-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dodadoa** [comment]
yay

**Comment by 0pdd** [comment]
The puzzle `1-f7fafd1b` has disappeared from the source code, that's why I closed this issue.
