### ISSUE TITLE
Implement Hamburger menu according to design.

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#37]
The puzzle `1-804aa44c` from #1 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/07762ca9a76792d7a6a37b927c0ac6c676f7dc34/src/components/MainLayout.js#L99-L99

The puzzle was created by Thai Pangsakulyanont on 19-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dtinth** [comment]
Right now it looks like this:

![image](https://user-images.githubusercontent.com/193136/54659044-de1d7100-4b02-11e9-8d6c-8a6606531fc6.png)

Design:

![image](https://user-images.githubusercontent.com/193136/54659079-0b6a1f00-4b03-11e9-828e-fffcab04785e.png)

**Comment by 0pdd** [comment]
The puzzle `1-804aa44c` has disappeared from the source code, that's why I closed this issue.
