### ISSUE TITLE
Polish design of NationwideSummaryHeader according to the design.

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#41]
The puzzle `1-675aeca2` from #1 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/49db4a1ab89be3171859bedde181a65f5e785e2b/src/components/NationwideSummaryView.js#L36-L36

The puzzle was created by Thai Pangsakulyanont on 19-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dtinth** [comment]
![Artboard](https://user-images.githubusercontent.com/193136/54624630-53a42580-4aa0-11e9-8595-0fc954a03814.png)

**Comment by p16i** [comment]
I think we can close this one. 

<img width="559" alt="image" src="https://user-images.githubusercontent.com/1214890/54777777-a539e500-4c45-11e9-810e-db14b58d683c.png">
