### ISSUE TITLE
Implement ZoneMasterView

### ISSUE THREAD

**Issue by dtinth** [codeforthailand/election-live#42]
![image](https://user-images.githubusercontent.com/193136/54626841-a089fb00-4aa4-11e9-9b93-ab53c97aee16.png)

**Comment by 0pdd** [comment]
@dtinth 2 puzzles [#43](https://github.com/codeforthailand/election-live/issues/43), [#44](https://github.com/codeforthailand/election-live/issues/44) are still not solved.

**Comment by 0pdd** [comment]
@dtinth 2 puzzles [#43](https://github.com/codeforthailand/election-live/issues/43), [#51](https://github.com/codeforthailand/election-live/issues/51) are still not solved; solved: [#44](https://github.com/codeforthailand/election-live/issues/44).

**Comment by 0pdd** [comment]
@dtinth the puzzle [#43](https://github.com/codeforthailand/election-live/issues/43) is still not solved; solved: [#44](https://github.com/codeforthailand/election-live/issues/44), [#51](https://github.com/codeforthailand/election-live/issues/51).

**Comment by 0pdd** [comment]
@dtinth all 3 puzzles are solved here: [#43](https://github.com/codeforthailand/election-live/issues/43), [#44](https://github.com/codeforthailand/election-live/issues/44), [#51](https://github.com/codeforthailand/election-live/issues/51).

**Comment by dtinth** [comment]
Done!
