### ISSUE TITLE
Create a 1st version of ZoneSearchField component in place of the Placeholder. May be a dummy component.

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#49]
The puzzle `1-a2cb78b6` from #1 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/843128114e9e7345e8a2d3156089c89d841bb352/src/components/ZoneMasterView.js#L74-L75

The puzzle was created by Thai Pangsakulyanont on 20-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dtinth** [comment]
![image](https://user-images.githubusercontent.com/193136/54661914-93a1f180-4b0e-11e9-9f98-7820e3872a01.png)

**Comment by p16i** [comment]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/1214890/54764351-2aaf9c00-4c2a-11e9-820c-2db8df8c3bd4.png">
