### ISSUE TITLE
Create a 1st version of ZoneFilterPanel component in place of the Placeholder. May be a dummy component.

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#50]
The puzzle `1-13da9db6` from #1 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/843128114e9e7345e8a2d3156089c89d841bb352/src/components/ZoneMasterView.js#L81-L82

The puzzle was created by Thai Pangsakulyanont on 20-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dtinth** [comment]
Context:

![image](https://user-images.githubusercontent.com/193136/54678318-72093000-4b37-11e9-8915-e8443a50b489.png)

Design:

![image](https://user-images.githubusercontent.com/193136/54661930-a1f00d80-4b0e-11e9-9de0-abb0be3ef680.png)

**Comment by p16i** [comment]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/1214890/54764389-431fb680-4c2a-11e9-9ad3-5008bce1892b.png">
