### ISSUE TITLE
Implement the first version of mobile tabs May be a dummy component that looks like the real one.

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#51]
The puzzle `42-9a011cc1` from #42 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/843128114e9e7345e8a2d3156089c89d841bb352/src/components/ZoneMasterView.js#L126-L127

The puzzle was created by Thai Pangsakulyanont on 20-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dtinth** [comment]
This mobile tab component is displayed at the bottom of the screen. To let user pick between content view and map view.

![image](https://user-images.githubusercontent.com/193136/54661965-c8ae4400-4b0e-11e9-9449-2c974b02c41c.png)

**Comment by p16i** [comment]
<img width="559" alt="image" src="https://user-images.githubusercontent.com/1214890/54768447-c2fd4f00-4c31-11e9-9444-fbb92b424d48.png">
