### ISSUE TITLE
Hamburger menu looks strange on  iOS

### ISSUE THREAD

**Issue by p16i** [codeforthailand/election-live#65]
<img width="559" alt="image" src="https://user-images.githubusercontent.com/1214890/54746808-afd18b80-4bff-11e9-9edf-914dc91861c8.png">

**Comment by dtinth** [comment]
Thanks for the issue... However the hamburger menu will be replaced with a navigation **dropdown** according to latest designs yesterday krubb. Sorry for the confusion.

**Comment by p16i** [comment]
np, feel free to close it if it's irrelevant.

**Comment by dtinth** [comment]
We’ve updated the nav — closing
