### ISSUE TITLE
Connect the mobile tabs to routing.

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#70]
The puzzle `1-d680e1f5` from #1 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/b834ca33b7d16fd0e7a7c4bcca497785ac9aba51/src/components/ZoneMasterView.js#L219-L219

The puzzle was created by Thai Pangsakulyanont on 22-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by p16i** [comment]
related to https://github.com/codeforthailand/election-live/issues/76

**Comment by 0pdd** [comment]
The puzzle `1-d680e1f5` has disappeared from the source code, that's why I closed this issue.
