### ISSUE TITLE
[UI polish] Polish the spacing in ZoneSearchPanel to match the design.

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#77]
The puzzle `1-9ac29d92` from #1 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/43fd6c51760518b9e6922ca37d0a9b2bfbb3a801/src/components/ZoneSearchPanel.js#L9-L9

The puzzle was created by Thai Pangsakulyanont on 22-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dtinth** [comment]
Design: https://invis.io/N6R20KQW2H7#/353489491_Search_Results_-_Mobile_-_Modal

![image](https://user-images.githubusercontent.com/193136/54811366-1ebfea80-4cbb-11e9-901e-494139598bc3.png)

Problems right now:

- Color not matching (too black).
- Spacing (too much).
- No right arrow at the right.

**Comment by 0pdd** [comment]
The puzzle `1-9ac29d92` has disappeared from the source code, that's why I closed this issue.

**Comment by dtinth** [comment]
Fixed in #80
