### ISSUE TITLE
Support text overflow on party list name

### ISSUE THREAD

**Issue by RbaduMan** [codeforthailand/election-live#84]
<img width="373" alt="Screen Shot 2562-03-22 at 23 21 04" src="https://user-images.githubusercontent.com/34000537/54837523-33bb6e80-4cf9-11e9-8464-bbfb7c16d370.png">

**Comment by p16i** [comment]
already done:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/1214890/54864541-5d24da80-4d8b-11e9-9d57-c0440fcf8921.png">
