### ISSUE TITLE
Update zone filtering logic to allow searching by postal code

### ISSUE THREAD

**Issue by 0pdd** [codeforthailand/election-live#89]
The puzzle `1-8bf3c6db` from #1 has to be resolved: 

https://github.com/codeforthailand/election-live/blob/b4f43608ac540cf9025bff893a0b90a2aa8b2e07/src/components/ZoneSearchPanel.js#L58-L58

The puzzle was created by Supanat Pothivarakorn on 22-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dtinth** [comment]
ตอนนี้น่าค้นหาเขตเลือกตั้ง สามารถค้นหาด้วยชื่อจังหวัดได้แล้ว แต่ยังค้นหาด้วยรหัสไปรษณีย์ไม่ได้

เรามีข้อมูล Map จากรหัสไปรษณีย์ไปยังเขตการเลือกตั้งต่างๆ

https://github.com/codeforthailand/dataset-election-62-candidates/blob/master/election62/statics/postcode-to-zones.json

แต่ไฟล์ข้อมูลนี้ยังไม่มี provinceId

**Comment by wiput1999** [comment]
อยากลองทำครับ~

**Comment by dtinth** [comment]
@wiput1999 Please do, and please keep me updated, thanks krub!

**Comment by whs** [comment]
Map เขตเลือกตั้งกับรหัสไปรษณีย์ให้ใน #159 แล้วนะครับ @wiput1999 

หรือถ้าจะ disown issue ผมจะลอง implement ที่เหลือให้ได้ครับ

**Comment by p16i** [comment]
@whs @wiput1999 how would you plan to apply filter for postcode in `_zones.json`? I guess we would need to visit every zones and check each postcode. 

Maybe we should consider create a mapping from postcode to zones. The lookup process will take O(1). We can also use regex to detect whether the user is searching by address or postcode.

**Comment by dtinth** [comment]
Let's give this issue to @whs 

We used a fuzzy search library to filter for zone already... I think a lookup table may not be necessary, as search-by-postcode operation is not "hot" (meaning may be called inside a loop, like getPartyById).

**Comment by whs** [comment]
Totally forgot to check my email.

I think the plan for now is to use regex to detect search type then a) if looks like postcode, then do postcode search only b) otherwise use fuse. Fuse implement sort by scoring, so it would be hard to implement a) merged into full text search result.

I believe we should do prefix matching which you can't lookup on table. If you want to optimize, go for trie which I think is premature optimization at this point.
